# Generated by Django 6.0.6 on 2026-06-09 13:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0003_alter_category_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=20, verbose_name='Номер счёта')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Баланс')),
                ('salary_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма зарплаты')),
                ('salary_day', models.PositiveSmallIntegerField(default=0, help_text='0 = последний день месяца, 1-28 = конкретное число', validators=[django.core.validators.MaxValueValidator(28)], verbose_name='День зарплаты')),
                ('salary_enabled', models.BooleanField(default=True, verbose_name='Зарплата включена')),
                ('last_salary_date', models.DateField(blank=True, null=True, verbose_name='Последнее начисление ЗП')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Банковский счёт',
                'verbose_name_plural': 'Банковские счета',
            },
        ),
        migrations.CreateModel(
            name='AutoCategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Ключевое слово')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_rules', to='finances.category', verbose_name='Категория')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rules', to='accounts.bankaccount', verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'Правило автокатегории',
                'verbose_name_plural': 'Правила автокатегорий',
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Пополнение'), ('out', 'Списание')], max_length=3, verbose_name='Направление')),
                ('source', models.CharField(choices=[('salary', 'Зарплата'), ('manual_topup', 'Ручное пополнение'), ('payment', 'Оплата'), ('scheduled', 'Запланированный платёж')], max_length=15, verbose_name='Источник')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата')),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Баланс после')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions', to='finances.category', verbose_name='Категория')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.bankaccount', verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'Операция по счёту',
                'verbose_name_plural': 'Операции по счёту',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('kind', models.CharField(choices=[('subscription', 'Подписка (авто)'), ('manual', 'Ручной платёж')], default='manual', max_length=15, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='0 = последний день месяца, 1-28 = конкретное число', validators=[django.core.validators.MaxValueValidator(28)], verbose_name='День списания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_paid_date', models.DateField(blank=True, null=True, verbose_name='Последнее списание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_payments', to='accounts.bankaccount', verbose_name='Счёт')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_payments', to='finances.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Запланированный платёж',
                'verbose_name_plural': 'Запланированные платежи',
                'ordering': ['day_of_month', 'name'],
            },
        ),
    ]
