# Generated by Django 6.0.1 on 2026-01-25 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylimit',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_limits', to='finances.category', verbose_name='Категория'),
        ),
    ]
