# Generated by Django 6.0.1 on 2026-01-25 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='categorylimit',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_limits', to='budget.monthlybudget', verbose_name='Бюджет'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlybudget',
            unique_together={('user', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='categorylimit',
            unique_together={('budget', 'category')},
        ),
    ]
