# Generated by Django 6.0.6 on 2026-06-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Иконка'),
        ),
    ]
